[book]
authors = ["Henry de Valence"]
language = "en"
multilingual = false
src = "notes"
title = "Penumbra"

[preprocessor.katex]

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
curly-quotes = true
fold = { enable = true, level = 1 }
git-repository-url = "https://github.com/penumbra-zone/penumbra"


