[workspace]

members = [
  "penumbrad",
  "tower-abci",
]

## Used for tower-abci

[patch.crates-io]
tracing = { git = "https://github.com/tokio-rs/tracing/", branch = "v0.1.x" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing/", branch = "v0.1.x" }