{{- if .Values.ingress.enabled }}
{{ $count := (.Values.numFullNodes | int) }}
{{/*
Each fullnode instance will have its pd and tendermint rpc ports
backing the exposed LoadBalancer service.
*/}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "penumbra.fullname" . }}-https
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.grpc }}`)
    services:
{{ range $i,$e := until $count }}
{{ $svc_name := printf "%s-p2p-fn-%d" (include "penumbra.fullname" $) $i }}
    - name: {{ include "penumbra.fullname" . }}-p2p-fn-0
      port: 8080
      scheme: h2c
{{ end }}
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.rpc }}`)
    services:
{{ range $i,$e := until $count }}
{{ $svc_name := printf "%s-p2p-fn-%d" (include "penumbra.fullname" $) $i }}
    - name: {{ $svc_name }}
      port: 26657
{{ end }}
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.grafana }}`)
    services:
    - name: {{ include "penumbra.fullname" . }}-metrics-grafana
      port: 80
  tls:
    domains:
    - main: {{ .Values.ingress.hosts.grpc }}
      sans:
        - {{ .Values.ingress.hosts.rpc }}
        - {{ .Values.ingress.hosts.grafana }}
    secretName: {{ include "penumbra.fullname" . }}-wildcard
{{- end }}
