name: Render and Deploy Notes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: Render and Deploy Notes
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Load get-version action to grab version component of deployment path
      uses: battila7/get-version-action@v2
      id: get_version

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install mdbook
      run: |
        cargo install mdbook mdbook-katex
    
    - name: Build Penumbra notes
      run: |
        mdbook build

    - name: Move notes to subdirectory
      run: |
        mkdir firebase-tmp
        mv book firebase-tmp/${{ steps.get_version.outputs.version }}
    
    - name: Deploy notes to firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: penumbra-e3789
